version: "3"

services:
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - POSTGRES_DB=idp
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin